global SavePath "~/Dropbox/Projects/RA/save"
global DataPath "~/Dropbox/Projects/RA/data"


/***************************************************************************************************

***************************************************************************************************/
insheet using "$DataPath/xxxx", clear tab
append using...

save "$DataPath/billionaireslit"


/***************************************************************************************************

***************************************************************************************************/


replace name = "Johnson-Marquart, Winnie" if name == "Johnson-Marquart, Winifred"
replace name = "Ford, Gerald" if name == "Ford, Gerald J."
replace name = "Chang, Jin Sook & Do Won" if name == "Chang, Do Won & Jin Sook"
replace name = "Dangermond, Jack" if name == "Dangermond, Jack & Laura"
replace name = "Ilitch, Marian" if name == "Ilitch, Michael & Marian"
replace name = "Newhouse, Samuel Jr." if name == "Newhouse, Samuel Irving Jr."
replace name = "Wexner, Leslie" if name == "Wexner, Les"
replace name = "Turner, Robert Edward III" if name == "Turner, Ted"
replace name = "Gates, William Henry III" if name == "Gates, Bill"
replace name = "Lerner, Theodore Nathan" if name == "Lerner, Ted"
replace name = "Ellison, Lawrence Joseph" if name == "Ellison, Larry"
replace name = "Bass, Sid Richardson" if name == "Bass, Sid"
replace name = "Ilitch, Michael" if name == "Ilitch, Marian"
replace name = "Ingram, Martha Robinson Rivers" if name == "Ingram, Martha"
replace name = "Whitman, Margaret C" if name == "Whitman, Meg"
replace name = "Stryker, Patricia A Short" if name == "Stryker, Pat"
replace name = "Jamail, Joseph Dahr Jr" if name == "Jamail, Joe Jr."
replace name = "Bass, Lee Marshall" if name == "Bass, Lee"
replace name = "Gross, William H" if name == "Gross, Bill"
replace name = "Wynn, Stephen A" if name == "Wynn, Steve"
replace name = "Golisano, Blase Thomas" if name == "Golisano, Tom"
replace name = "Mars, John Franklyn" if name == "Mars, John"
replace name = "Fisher, Doris Feigenbaum" if name == "Fisher, Doris"
replace name = "Chang, Do Won" if name == "Chang, Jin Sook & Do Won"
replace name = "Knight, Philip Hampson" if name == "Knight, Phil"
replace name = "York, Denise Debartolo" if name == "York, Denise"
replace name = "Koch, David Hamilton" if name == "Koch, David"
replace name = "Jones, Jerral Wayne" if name == "Jones, Jerry"
replace name = "Love, Tom" if name == "Love, Tom & Judy"
replace name = "Koch, Charles de Ganahl" if name == "Koch, Charles"
replace name = "Taylor, Jack Crawford" if name == "Taylor, Jack"
replace name = "Pritzker, James" if name == "Pritzker, Jennifer"
replace name = "Lee, Thomas Haskell" if name == "Lee, Thomas"
replace name = "Allen, Paul Gardner" if name == "Allen, Paul"
replace name = "Ziff, Dirk Edward" if name == "Ziff, Dirk"
replace name = "Butt, Charles Clarence" if name == "Butt, Charles"
replace name = "Koch, William Ingraham" if name == "Koch, William"
replace name = "Icahn, Carl Celian" if name == "Icahn, Carl"
replace name = "Hughes, Bradley Wayne" if name == "Hughes, B. Wayne"
replace name = "Hunt, William Herbert" if name == "Hunt, W. Herbert"
replace name = "Ballmer, Steven Anthony" if name == "Ballmer, Steve"
replace name = "Ricketts, J Joseph" if name == "Ricketts, J. Joe"
replace name = "Kennedy, James" if name == "Kennedy, Jim"
replace name = "Anschutz, Philip Frederick" if name == "Anschutz, Philip"
replace name = "Resnick, Stewart" if name == "Resnick, Stewart and Lynda"
replace name = "Meijer, Hank" if name == "Meijer, Hank & Doug"
replace name = "Mansueto, Joseph D" if name == "Mansueto, Joe"
replace name = "Ziff, Daniel Morton" if name == "Ziff, Daniel"
replace name = "Sarofim, Fayez Shalaby" if name == "Sarofim, Fayez"
replace name = "Dolan, Charles Francis" if name == "Dolan, Charles"
replace name = "Wexner, Leslie Herbert" if name == "Wexner, Leslie"
replace name = "Cherng, Andrew" if name == "Cherng, Andrew & Peggy"
replace name = "Fisher, Kenneth L" if name == "Fisher, Ken"
replace name = "Saul, Bernard Francis II" if name == "Saul, Bernard II."
replace name = "Johnson, Charles Bartlett" if name == "Johnson, Charles"
replace name = "Skoll, Jeffery" if name == "Skoll, Jeffrey"
replace name = "Ryan, Patrick George" if name == "Ryan, Patrick"
replace name = "Rich, Robert Edward Jr" if name == "Rich, Robert Jr."
replace name = "Perot, Henry Ross Jr" if name == "Perot, H. Ross Jr."
replace name = "Perot, Henry Ross Sr" if name == "Perot, H. Ross Sr."
replace name = "Jacobs, Jeremy Maurice Sr" if name == "Jacobs, Jeremy Sr."
replace name = "Nicholas, Henry Thompson III" if name == "Nicholas, Henry III."
replace name = "Griffin, Kenneth C" if name == "Griffin, Ken"
replace name = "Bass, Edward Perry" if name == "Bass, Edward"
replace name = "Ziff, Robert David" if name == "Ziff, Robert"
replace name = "Stryker, Jon Lloyd" if name == "Stryker, Jon"
replace name = "Bacon, Louis Moore" if name == "Bacon, Louis"
replace name = "Bren, Donald Leroy" if name == "Bren, Donald"
replace name = "Murdock, David Howard" if name == "Murdock, David"
replace name = "Peery, Richard Taylor" if name == "Peery, Richard"
replace name = "Lauder, Ronald Steven" if name == "Lauder, Ronald"
replace name = "Stern, Leonard Norman" if name == "Stern, Leonard"
replace name = "DeVos, Richard Marvin" if name == "DeVos, Richard"
replace name = "Smith, Frederick Wallace" if name == "Smith, Frederick"
replace name = "Mars, Forrest Edward Jr" if name == "Mars, Forrest Jr."
replace name = "Blavatnik, Leonard" if name == "Blavatnik, Len"
replace name = "Buffett, Warren Edward" if name == "Buffett, Warren"
replace name = "Milken, Michael Robert" if name == "Milken, Michael"
replace name = "Bechtel, Stephen Davison Jr" if name == "Bechtel, Stephen Jr."
replace name = "Getty, Gordon Peter" if name == "Getty, Gordon"
replace name = "Michelson, Gary Karlin" if name == "Michelson, Gary"
replace name = "Bluhm, Neil Gary" if name == "Bluhm, Neil"
replace name = "Moore, Gordon Earle" if name == "Moore, Gordon"
replace name = "Zuckerman, Mortimer Benjamin" if name == "Zuckerman, Mortimer"
replace name = "Taubman, Adolph Alfred" if name == "Taubman, Alfred"
replace name = "Bezos, Jeffrey P" if name == "Bezos, Jeff"
replace name = "Catsimatidis, John Andreas" if name == "Catsimatidis, John"
replace name = "Johnson, Rupert Harris Jr" if name == "Johnson, Rupert Jr."
replace name = "Liebmann, Marianne Cargill" if name == "Liebmann, Marianne"
replace name = "Udvar-Hazy, Steven Ferencz" if name == "Udvar-Hazy, Steven"
replace name = "Redstone, Sumner Murray" if name == "Redstone, Sumner"
replace name = "Newhouse, Donald Edward" if name == "Newhouse, Donald"
replace name = "Huizenga, Harry Wayne" if name == "Huizenga, H. Wayne"
replace name = "Solow, Sheldon Henry" if name == "Solow, Sheldon"
replace name = "Bass, Robert Muse" if name == "Bass, Robert"
replace name = "Johnson, Edward Crosby III" if name == "Johnson, Edward III."
replace name = "Perenchio, Andrew Jerrold" if name == "Perenchio, A. Jerrold"
replace name = "Newhouse, Samuel Irving Jr" if name == "Newhouse, Samuel Jr."
replace name = "Sobrato, John Albert" if name == "Sobrato, John A."
replace name = "Murdoch, Keith Rupert" if name == "Murdoch, Rupert"
replace name = "Jacobs, Irwin Mark" if name == "Jacobs, Irwin"
replace name = "Trump, Donald John" if name == "Trump, Donald"
replace name = "Bloomberg, Michael Rubens" if name == "Bloomberg, Michael"
replace name = "Rainwater, Richard Edward" if name == "Rainwater, Richard"
replace name = "Hildebrand, Jeffrey" if name == "Hildebrand, Jeffery"
replace name = "Spielberg, Steven Allen" if name == "Spielberg, Steven"
replace name = "Zell, Samuel" if name == "Zell, Sam"
replace name = "Spangler, Clemmie Dixon Jr" if name == "Spangler, Clemmie Jr."
replace name = "Justice, Jim" if name == "Justice, Jim II."
replace name = "Argyros, George Leon" if name == "Argyros, George"
replace name = "Lauder, Leonard Alan" if name == "Lauder, Leonard"
replace name = "Hostetter, Amos Barr Jr" if name == "Hostetter, Amos Jr."
replace name = "Hubbard, Stanley Stub" if name == "Hubbard, Stanley"
replace name = "Perelman, Ronald Owen" if name == "Perelman, Ronald"
replace name = "Baron, Ronald" if name == "Baron, Ron"
replace name = "Pritzker, Jay Robert (J B)" if name == "Pritzker, Jay Robert (J.B.)"
replace name = "DeBartolo, Edward John Jr" if name == "DeBartolo, Edward Jr."
replace name = "Hillman, Henry Lea" if name == "Hillman, Henry"
replace name = "Burkle, Ronald" if name == "Burkle, Ron"
replace name = "Snyder, Daniel" if name == "Snyder, Dan"
replace name = "Kao, Min H" if name == "Kao, Min"
replace name = "Mandel, Stephen" if name == "Mandel, Stephen Jr."
replace name = "Emmerson, Archie Aldis (Red)" if name == "Emmerson, Archie Aldis"
replace name = "Greene, Jeffrey" if name == "Greene, Jeff"
replace name = "Cohen, Steven A" if name == "Cohen, Steve"
replace name = "Mathile, Clayton Lee" if name == "Mathile, Clayton"
replace name = "Parry-Okedon, Blair" if name == "Parry-Okeden, Blair"
replace name = "Spanos, Alexander Gus" if name == "Spanos, Alexander"
replace name = "Johnson, H Fisk" if name == "Johnson, H. Fisk"
replace name = "Davis, Ray C" if name == "Davis, Ray"
replace name = "Warner, H Ty" if name == "Warner, Ty"
replace name = "Gores, Tom T" if name == "Gores, Tom"
replace name = "Sanford, T Denny" if name == "Sanford, T. Denny"
replace name = "Menard, John R Jr" if name == "Menard, John Jr."
replace name = "Ross, Wilbur L Jr" if name == "Ross, Wilbur Jr."
replace name = "Walton, S Robson" if name == "Walton, S. Robson"
replace name = "Frist, Thomas F Jr" if name == "Frist, Thomas Jr."
replace name = "Abraham, S Daniel" if name == "Abraham, S. Daniel"
replace name = "Cook, Scott D" if name == "Cook, Scott"
replace name = "Brown, John W" if name == "Brown, John"
replace name = "Page, Larry E" if name == "Page, Larry"
replace name = "Shaw, David E" if name == "Shaw, David"
replace name = "Johnson, S Curtis" if name == "Johnson, S. Curtis"
replace name = "Reyes, M Jude" if name == "Reyes, Jude"
replace name = "Roski, Edward P Jr" if name == "Roski, Edward Jr."
replace name = "Tisch, Joan H" if name == "Tisch, Joan"
replace name = "White, Dean V" if name == "White, Dean"
replace name = "Walton, Jim C" if name == "Walton, Jim"
replace name = "Doerr, L John" if name == "Doerr, John"
replace name = "Cargill, James R II" if name == "Cargill, James II."
replace name = "Fisher, John J" if name == "Fisher, John"
replace name = "Ford, Gerald J" if name == "Ford, Gerald"
replace name = "Malone, John C" if name == "Malone, John"
replace name = "Kirk, Randal J" if name == "Kirk, Randal"
replace name = "Kelley, Brad M" if name == "Kelley, Brad"
replace name = "McCaw, Craig O" if name == "McCaw, Craig"
replace name = "Clark, James H" if name == "Clark, James"
replace name = "Perez, Jorge M" if name == "Perez, Jorge"
replace name = "Rennert, Ira L" if name == "Rennert, Ira"
replace name = "Kohler, Herbert V Jr" if name == "Kohler, Herbert Jr."
replace name = "Cargill, Austen S II" if name == "Cargill, Austen II."
replace name = "Metropoulos, C Dean" if name == "Metropoulos, C. Dean"
replace name = "France, James C" if name == "France, James"
replace name = "Kravis, Henry R" if name == "Kravis, Henry"
replace name = "Penske, Roger S" if name == "Penske, Roger"
replace name = "Walton, Alice L" if name == "Walton, Alice"
replace name = "Reyes, J Christopher" if name == "Reyes, J. Christopher"
replace name = "Blank, Arthur M" if name == "Blank, Arthur"
replace name = "Ross, Stephen M" if name == "Ross, Stephen"
replace name = "Rales, Steven M" if name == "Rales, Steven"
replace name = "Burrell, Gary L" if name == "Burrell, Gary"
replace name = "Simons, James H" if name == "Simons, James"
replace name = "Robertson, Julian H Jr" if name == "Robertson, Julian Jr."
replace name = "Pritzker, John A" if name == "Pritzker, John"
replace name = "Hayne, Richard A" if name == "Hayne, Richard"
replace name = "Fisher, Robert J" if name == "Fisher, Robert"
replace name = "Stryker, Ronda E" if name == "Stryker, Ronda"
replace name = "Siebel, Thomas M" if name == "Siebel, Thomas"
replace name = "Kaiser, George B" if name == "Kaiser, George"
replace name = "McNair, Robert C" if name == "McNair, Robert"
replace name = "Kellogg, Peter R" if name == "Kellogg, Peter"
replace name = "Bechtel, Riley P" if name == "Bechtel, Riley"
replace name = "Kinder, Richard D" if name == "Kinder, Richard"
replace name = "Omidyar, Pierre M" if name == "Omidyar, Pierre"
replace name = "Roberts, George R" if name == "Roberts, George"
replace name = "James, Hamilton E" if name == "James, Hamilton"
replace name = "Schwab, Charles R" if name == "Schwab, Charles"
replace name = "Fisher, William F" if name == "Fisher, William"
replace name = "Rales, Mitchell P" if name == "Rales, Mitchell"
replace name = "Lampert, Edward S" if name == "Lampert, Edward"
replace name = "Duffield, David A" if name == "Duffield, David"
replace name = "Schultz, Howard S" if name == "Schultz, Howard"
replace name = "Langone, Kenneth G" if name == "Langone, Kenneth"
replace name = "Schulze, Richard M" if name == "Schulze, Richard"
replace name = "Rizzuto, Leandro P" if name == "Rizzuto, Leandro"
replace name = "Pritzker, Thomas J" if name == "Pritzker, Thomas"
replace name = "Lindemann, George L" if name == "Lindemann, George"
replace name = "Bisciotti, Stephen J" if name == "Bisciotti, Stephen"
replace name = "Schwarzman, Stephen A" if name == "Schwarzman, Stephen"
replace name = "Scott, Walter Jr" if name == "Scott, Walter Jr."
replace name = "Cooperman, Leon G" if name == "Cooperman, Leon G."
replace name = "McLane, Drayton Jr" if name == "McLane, Drayton Jr."
replace name = "Coleman, Chase III" if name == "Coleman, Chase III."
replace name = "Wadhwani, Romesh T" if name == "Wadhwani, Romesh T."
replace name = "Conway, William Jr" if name == "Conway, William Jr."
replace name = "Wrigley, William Jr" if name == "Wrigley, William Jr."
replace name = "Fertitta, Frank III" if name == "Fertitta, Frank III."
replace name = "Jones, Paul Tudor II" if name == "Jones, Paul Tudor II."
replace name = "Yuengling, Richard Jr" if name == "Yuengling, Richard Jr."
replace name = "Rockefeller, David Sr" if name == "Rockefeller, David Sr."
tempfile temp
save `temp'
